spring.application.name=la-guarida-hecate

spring.datasource.url=jdbc:h2:mem:hecatedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true

spring.headers.frame-options=sameorigin

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.encoding=UTF-8

spring.jpa.defer-datasource-initialization=true