spring.application.name=hecate-backend
# Configuracion de la conexion a MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/hecate
spring.datasource.username=adminInes
spring.datasource.password=adminInes
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
server.port=8081

# Configuracion de JPA / Hibernate
# Esto permite que Java cree o actualice las tablas automaticamente si hay cambios
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect